### ISSUE TITLE
Is this package being maintained?

### ISSUE THREAD

**Issue by JF-626164** [Azure-OSS/azure-storage-php#26]
With the retirement of matthewbdaly/laravel-azure-storage, in its deprecation notice the owner recommends using this package. There are open issues & a PR from 2023, which leads me to ask, is this package being maintained?

**Comment by pimjansen** [comment]
> With the retirement of matthewbdaly/laravel-azure-storage, in its deprecation notice the owner recommends using this package. There are open issues & a PR from 2023, which leads me to ask, is this package being maintained?

Well we started but it seems not many ppl are interested so

**Comment by iamtomc** [comment]
I just wanted to ask the same question? so what is the way forward would there be any maintenance for the package?

**Comment by JF-626164** [comment]
A lot of people will be looking at using this package now that matthewbdaly/laravel-azure-storage is abandoned & recommending we use this package.

**Comment by pimjansen** [comment]
Well then we should start updating it since it is a mess how MS left jt behind

The tests are all integration tests erc
