### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by greyhoundrecycling** [Azure-OSS/azure-storage-php#33]
### Summary
PHP 8.3.9

Could not find a matching version of package azure-oss/azure-storage-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
### Versions

|                             | Version                  |
|:----------------------------|:-------------------------|
| PHP version                 | 8.3.9                    |
| Service                     | composer |
| `azure-storage-php` version | x.y.z                    |

### Self-enclosed code snippet for reproduction

```php
composer require azure-oss/azure-storage-php
```

### Expected output

```txt
Install the library
```

### Actual output

```txt
In PackageDiscoveryTrait.php line 376:

  Could not find a matching version of package azure-oss/azure-storage-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

**Comment by pimjansen** [comment]
Docs updated! Thanks for the headsup
