### ISSUE TITLE
BlobContainerClient marked as final, restricting mocks

### ISSUE THREAD

**Issue by 27pchrisl** [Azure-OSS/azure-storage-php#42]
Hi,

Thanks for the great library!

I'm testing code that uses the `BlobContainerClient` but because it is marked final I cannot mock it with Mockery.

For example, my code uses `$client->getBlobs()` and I would like to mock the return of some fake blobs.

Could the final keyword be dropped to enable mocking?

Thanks!

**Comment by brecht-vermeersch** [comment]
Hi. We use final as a way of preventing breaking changes when we change internals. I suggest writing your own abstraction around this package or using one of ours: 
https://github.com/Azure-OSS/azure-storage-php-adapter-laravel
https://github.com/Azure-OSS/azure-storage-php-adapter-flysystem

**Comment by 27pchrisl** [comment]
Ok, I had started doing that already 👍
